//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Lesson3Entities : DbContext
    {
        private static Lesson3Entities _context;
        public Lesson3Entities()
            : base("name=Lesson3Entities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public static Lesson3Entities GetContext()
        {
            if (_context == null)
                _context = new Lesson3Entities();

            return _context;
        }
        public virtual DbSet<admir> admir { get; set; }
        public virtual DbSet<basil> basil { get; set; }
        public virtual DbSet<petr> petr { get; set; }
        public virtual DbSet<Абонентское_оборудование> Абонентское_оборудование { get; set; }
        public virtual DbSet<Абоненты> Абоненты { get; set; }
        public virtual DbSet<Базовые_станции> Базовые_станции { get; set; }
        public virtual DbSet<Заявки_CRM> Заявки_CRM { get; set; }
        public virtual DbSet<Магистраль> Магистраль { get; set; }
        public virtual DbSet<Сети_доступа> Сети_доступа { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Тарифы> Тарифы { get; set; }
        public virtual DbSet<Тарифы_абонентов> Тарифы_абонентов { get; set; }
        public virtual DbSet<Информация_для_сотрудников> Информация_для_сотрудников { get; set; }
        public virtual DbSet<Платежи_абонентов> Платежи_абонентов { get; set; }
    }
}
