//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Базовые_станции
    {
        public string ID_базовой_станции { get; set; }
        public string Название_БС { get; set; }
        public string Площадь_зоны_покрытия_кв_км { get; set; }
        public string Частота_Гц { get; set; }
        public string Тип_антенны { get; set; }
        public string Диапазон_показателей_хэндовера { get; set; }
        public string Стандарт { get; set; }
        public string Координаты_установки { get; set; }
    }
}
