//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявки_CRM
    {
        public string номер_заявки { get; set; }
        public System.DateTime Дата_создания { get; set; }
        public int ЛС { get; set; }
        public string Услуга { get; set; }
        public string Вид_услуги { get; set; }
        public string Тип_услуги { get; set; }
        public string Статус { get; set; }
        public string Тип_оборудования { get; set; }
        public string Описание_проблемы { get; set; }
        public Nullable<System.DateTime> Дата_закрытия { get; set; }
        public string Тип_проблема { get; set; }
    }
}
