//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Платежи_абонентов
    {
        public string ID_платежа { get; set; }
        public System.DateTime Дата_платежа { get; set; }
        public string Сумма_платежа { get; set; }
        public string Баланс_абонента { get; set; }
        public System.DateTime Дата_баланса { get; set; }
        public string Задолженность { get; set; }
        public string Номер_абонента { get; set; }
    }
}
