//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сети_доступа
    {
        public string Серийный_номер { get; set; }
        public string Наименование_сетей_доступа { get; set; }
        public string количество_портов { get; set; }
        public string стандарт_передачи_данных { get; set; }
        public string частота { get; set; }
        public string интерфейсы { get; set; }
        public string скорость_передачи_данных { get; set; }
        public string место_расположения { get; set; }
    }
}
